base_dir "/home/karsten/chef/"
file_cache_path base_dir + "cache/"
cookbook_path base_dir + "cookbooks/"
data_bag_path base_dir + "data_bags/"
#encrypted_data_bag_secret "/home/karsten/chef/data_bag_key"
cookbook_path base_dir + "cookbooks/"
role_path base_dir + "roles/"
